services:
  samsung-tvplus:
    container_name: samsung-tvplus
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REGIONS=ca,gb,us
      - TZ=Europe/London
    ports:
      - 29001:80
    restart: unless-stopped

networks:
  default:
    name: samsung-tvplus-develop
